---
title: "ggplot2 Elegant Graphics for Data Analysis"
author: "QinQin0912"
date: "2015年12月5日"
output: word_document
subtitle: ggplot2 数据分析与图形艺术
---

##第一章 简介
一张统计图形就是从数据到几何对象的图形属性的一个映射。
此外，图形中还可能包含数据的统计变化，最后绘制在某个特定的坐标系，而分面则可用来生成数据不同子集的图形。
总而言之，一张统计图就是由上述这些独立的图形部件所组成的。

交互包：GGobi

##第二章 从qplot开始入门
```{r,results='hide'}
library(ggplot2)
set.seed(1410)##让样本可重复
diamonds
dsmall<-diamonds[sample(nrow(diamonds),100),]
```

```{r}
qplot(carat,price,data=diamonds)
```

```{r}
qplot(log(carat),log(price),data=diamonds)##Log关系下接近于线性
```

```{r}
qplot(carat,x*y*z,data=diamonds)##已有变量的某种组合
```

```{r}
qplot(carat,price,data=dsmall,colour=color)
qplot(carat,price,data=dsmall,shape=cut)
```

```{r}
qplot(carat,price,data=diamonds,alpha=I(1/10))##半透明颜色可以有效减轻图形元素重叠的现象
qplot(carat,price,data=diamonds,alpha=I(1/100))
qplot(carat,price,data=diamonds,alpha=I(1/200))
```

不同类型的变量有不同适用的图形属性。颜色和形状适合于分类变量，而大小适合于连续变量。
如果数据量很大，那么不同组的数据之间就很难进行区分。

```{r}
qplot(carat,price,data=dsmall,geom=c("point","smooth"))
qplot(carat,price,data=diamonds,geom=c("point","smooth"))
```

se=FALSE,不绘制标准差

```{r}
qplot(carat,price,data=dsmall,geom=c("point","smooth"),span=0.2)#平滑参数
qplot(carat,price,data=dsmall,geom=c("point","smooth"),span=1)
```
　
```{r}
library(mgcv)#与lm使用的样条相类似,但样条的阶数是通过数据估计得到的，bs="cs"是数据量超过1000时默认使用的选项 
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="gam",formula=y~s(x))
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="gam",formula=y~s(x,bs="cs"))
```

```{r}
library(splines)
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="lm")
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="lm",formula=y~ns(x,5))#自由度取值越大，曲线的波动也越大 
```

```{r}
qplot(color,price/carat,data=diamonds,geom="jitter",alpha=I(1/5))
qplot(color,price/carat,data=diamonds,geom="jitter",alpha=I(1/50))
qplot(color,price/carat,data=diamonds,geom="jitter",alpha=I(1/200))#看出数据集中的地方
```

```{r}
qplot(carat,data=diamonds,geom="histogram")
qplot(carat,data=diamonds,geom="density")
```

```{r}
qplot(carat,data=diamonds,geom="histogram",binwidth=1,xlim=c(0,3))
qplot(carat,data=diamonds,geom="histogram",binwidth=0.1,xlim=c(0,3))
qplot(carat,data=diamonds,geom="histogram",binwidth=0.01,xlim=c(0,3))
```

```{r}
qplot(carat,data=diamonds,geom="density",colour=color)
qplot(carat,data=diamonds,geom="histogram",colour=color)
```

```{r}
qplot(color,data=diamonds,geom="bar")
qplot(color,data=diamonds,geom="bar",weight=carat)+scale_y_continuous("caret")#加权后的汇总
```

```{r}
qplot(date,unemploy/pop,data=economics,geom="line")
qplot(date,uempmed,data=economics,geom="line")
```

```{r}
year<-function(x)as.POSIXlt(x)$year+1900
qplot(unemploy/pop,uempmed,data=economics,geom=c("point","path"))
qplot(unemploy/pop,uempmed,data=economics,geom="path",colour=year(date))
```

```{r}
qplot(carat,data=diamonds,facets=color~.,geom="histogram",binwidth=0.1,xlim=c(0,3))
qplot(carat,..density..,data=diamonds,facets=color~.,geom="histogram",binwidth=0.1,xlim=c(0,3))
```

```{r}
qplot(
  carat,price,data=dsmall,
  xlab="Price($)",ylab="Weight(carats)",main="Price-weight relationship"
)
qplot(
carat,price/carat,data=dsmall,
ylab=expression(frac(price,carat)),
xlab="Weight(carats)",
main="Small diamonds",
xlim=c(.2,1)
)
```

```{r}
qplot(carat,price,data=dsmall,log="xy")
```





