---
title: "第五章 工具箱"
subtitle: "ggplot2 数据分析与图形艺术"
author: "QinQin0912"
date: "2015年12月5日"
output: html_document
---
  #图形叠加的总体策略
  ##用以展示数据本身
  ##用以展示数据的统计摘要
  ##用以添加额外的元数据
  
  #基本图形类型
  
  ```{r}
library(ggplot2)
df<-data.frame(
  x=c(3,1,5),
  y=c(2,4,6),
  label=c("a","b","c")
)
p<-ggplot(df,aes(x,y))+xlab(NULL)+ylab(NULL)
p+geom_point()+labs(title="geom_point")
p+geom_bar(stat = "identity")+labs(title="geom_bar(stat=\"identity\")")
p+geom_line()+labs(title="geom_line")
p+geom_area()+labs(title="geom_area")
p+geom_path()+labs(title="geom_path")
p+geom_text(aes(label=label))+labs(title="geom_text")
p+geom_tile()+labs(title="geom_tile")
p+geom_polygon()+labs(title="geom_polygon")
```

```{r}
depth_dist<-ggplot(diamonds,aes(depth))+xlim(58,63)
depth_dist+geom_histogram(aes(y=..density..),binwidth=0.1)+facet_grid(cut~.)
depth_dist+geom_histogram(aes(fill=cut),binwidth=0.1,position="fill")
depth_dist+geom_freqpoly(aes(y=..density..,colour=cut),binwidth=0.1)
```

```{r}
library(plyr)
qplot(cut,depth,data=diamonds,geom="boxplot")#类别型变量
qplot(carat,depth,data=diamonds,geom="boxplot",group=round_any(carat,0.1,floor),xlim=c(0,3))#连续型变量
```

```{r}
qplot(class,cty,data=mpg,geom="jitter")
qplot(class,drv,data=mpg,geom="jitter")
```

```{r}
qplot(depth,data=diamonds,geom="density",xlim=c(54,70))
qplot(depth,data=diamonds,geom="density",xlim=c(54,70),fill=cut,alpha=I(0.2))
```

```{r}
library(ggplot2)
df<-data.frame(x=rnorm(2000),y=rnorm(2000))
norm<-ggplot(df,aes(x,y))
norm+geom_point()
norm+geom_point(shape=1)
norm+geom_point(shape=".")
norm+geom_point(colour="black",alpha=1/3)
norm+geom_point(colour="black",alpha=1/5)
norm+geom_point(colour="black",alpha=1/10)
```

```{r}
td<-ggplot(diamonds,aes(table,depth))+xlim(50,70)+ylim(50,70)
td+geom_point()
td+geom_jitter()
jit<-position_jitter(width=0.5)
td+geom_point(position = jit)
td+geom_point(position = jit,colour="black",alpha=1/10)
td+geom_point(position = jit,colour="black",alpha=1/50)
td+geom_point(position = jit,colour="black",alpha=1/200)#绘制遮盖图是一种二维核密度估计问题
```

```{r}
d<-ggplot(diamonds,aes(carat,price))+xlim(1,3)+theme(legend.position="none")
d + stat_bin2d()
d + stat_bin2d(bins=10)
d + stat_bin2d(binwidth=c(0.02,200))
d + stat_binhex()
d + stat_binhex(bins=10)
d + stat_binhex(binwidth=c(0.02,200))
```

```{r}
d<-ggplot(diamonds,aes(carat,price))+xlim(1,3)+theme(legend.position="none")
d+geom_point()+geom_density2d()
d+stat_density2d(geom="point",aes(size=..density..),contour=F)+scale_size_area()
#基于等高线的密度展示
d+stat_density2d(geom="tile",aes(fill=..density..),contour=F)
last_plot()+scale_fill_gradient(limits=c(1e-5,8e-4))
#基于色深的密度展示
```

```{r}
library(maps)
data(us.cities)
big_cities<-subset(us.cities,pop>500000)
qplot(long,lat,data=big_cities)+borders("state",size=0.5)
tx_cities<-subset(us.cities,country.etc == "TX")
ggplot(tx_cities,aes(long,lat))+
  borders("country","texas",colour="grey70")+
  geom_point(colour="black",alpha=0.5)
```

```{r}
library(maps)
states<-map_data("state")
arrests<-USArrests
names(arrests)<-tolower(names(arrests))
arrests$region<-tolower(rownames(USArrests))

choro<-merge(states,arrests,by="region")
choro<-choro[order(choro$order),]

qplot(long,lat,data=choro,group=group,fill=assault,geom="polygon")
qplot(long,lat,data=choro,group=group,fill=assault/murder,geom="ploygon")
```

```{r}
library(plyr)
ia<-map_data("county","iowa")
mid_range<-function(x)mean(range(x,na.rm=TRUE))
centres<-ddply(ia, .(subregion),colwise(mid_range,.(lat,long)))
ggplot(ia,aes(long,lat))+
  geom_polygon(aes(group=group),fill=NA,colour="grey60")+
  geom_text(aes(label=subregion),data=centres,
            size=2,angle=45
            )
```

#揭示不确定性

```{r}
d<-subset(diamonds,carat<2.5&
            rbinom(nrow(diamonds),1,0.2)==1)
d$lcarat<-log10(d$carat)
d$lprice<-log10(d$price)
#剔除整体的线性趋势
detrend<-lm(lprice~lcarat,data=d)
d$lprice2<-resid(detrend)

mod<-lm(lprice2~lcarat*color,data=d)

library(effects)
effectdf<-function(...) {
  suppressWarnings(as.data.frame(effect(...)))
}

color<-effectdf("color",mod)
both1<-effectdf("lcarat:color",mod)

carat<-effectdf("lcarat",mod,default.levels=50)
both2<-effectdf("lcarat:color",mod,default.levels=3)
#剔除非线性性
qplot(lcarat,lprice,data=d,colour=color)
#剔除了主要的线性趋势
qplot(lcarat,lprice2,data=d,colour=color)

#color的边际效应和条件效应
fplot<-ggplot(mapping=aes(y=fit,ymin=lower,ymax=upper))+ylim(range(both2$lower,both2$upper))
fplot%+%color+aes(x=color)+geom_point()+geom_errorbar()
fplot%+%both2+
  aes(x=color,colour=lcarat,group=interaction(color,lcarat))+geom_errorbar()+geom_line(aes(group=lcarat))+scale_colour_gradient()

fplot%+%carat+aes(x=lcarat)+geom_smooth(stat="identity")

ends<-subset(both1,lcarat==max(lcarat))
fplot%+%both1+aes(x=lcarat,colour=color)+
  geom_smooth(stat="identity")+
  scale_colour_hue()+theme(legend.position="none")+
  geom_text(aes(label=color,x=lcarat+0.02),ends)
```
