---
title: "第六章 标度 坐标轴 图例"
subtitle: "ggplot2 数据分析与图形艺术"
author: "QinQin0912"
date: "2015年12月5日"
output: html_document
---

```{r}
plot<-qplot(cty,hwy,data=mpg)
plot+aes(x=drv)
plot+aes(x=drv)+scale_x_discrete()
plot
```

```{r}
p<-qplot(sleep_total,sleep_cycle,data=msleep,colour=vore)
p
##显式添加默认标度
p+scale_colour_hue()
##修改默认标度的参数,这里改变了图例的外观
p+scale_colour_hue("What does\nit eat?",
                   breaks=c("herbi","carni","omin",NA),
                   labels=c("plants","meats","both","don't know"))
##使用一种不同的标度
p+scale_colour_brewer(palette = "Set1")
```

```{r}
p<-qplot(cty,hwy,data=mpg,colour=displ)
p
p+scale_x_continuous("City mpg")
p+xlab("City mpg")
p+ylab("Highway mpg")
p+labs(x="City mpg",y="Highway",colour="Displacement")
p+xlab(expression(frac(miles,gallon)))
```

```{r}
p<-plot(cyl,wt,data=mtcars)
p
p+scale_x_continuous(breaks=c(5.5,6.5))
p+scale_x_continuous(limits=c(5.5,6.5))
p<-qplot(wt,cyl,data=mtcars,colour=cyl)
p
p+scale_colour_gradient(breaks=c(5.5,6.5))#影响坐标轴图例
p+scale_colour_gradient(limits=c(5.5,6.5))#影响在图形上的元素
```

```{r}
library(ggplot2)
qplot(log10(carat),log10(price),data=diamonds)
qplot(carat,price,data=diamonds)+scale_x_log10()+scale_y_log10()
#图形主体是完全相同的,但坐标轴上的标签是不同的。
```

```{r}
library(scales)
plot<-qplot(date,psavert,data=economics,geom="line")+
  ylab("Personal savings rate")+
  geom_hline(xintercept=0,colour="grey50")
plot
plot+scale_x_date(breaks=date_breaks("10 years"))
plot+scale_x_date(
  limits=as.Date(c("2004-01-01","2005-01-01")),
  labels=date_format("%Y-%M-%d")
)
```

```{r}
f2d<-with(faithful,MASS::kde2d(eruptions,waiting,h=c(1,10),n=50))
df<-with(f2d,cbind(expand.grid(x,y),as.vector(z)))
names(df)<-c("eruptions","waiting","density")
erupt<-ggplot(df,aes(waiting,eruptions,fill=density))+
  geom_tile()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))
erupt+scale_fill_gradient(limits=c(0,0.04))
erupt+scale_fill_gradient(limits=c(0,0.04),low="white",high="black")
erupt+scale_fill_gradient2(limits=c(-0.04,0.04),midpoint = mean(df$density))
```

```{r}
library(grid)
library(vcd)
fill_gradn<-function(pal){
  scale_fill_gradientn(colours=pal(7),limits=c(0,0.04))}
erupt + fill_gradn(rainbow_hcl)
erupt + fill_gradn(diverge_hcl)
erupt + fill_gradn(heat_hcl)
```

```{r}
point<-qplot(brainwt,bodywt,data=msleep,log="xy",colour=vore)
area<-qplot(log10(brainwt),data=msleep,fill=vore,binwidth=1)
point+scale_colour_brewer(palette="Set1")
point+scale_colour_brewer(palette = "Set2")
point+scale_colour_brewer(palette = "Pastel1")
area+scale_fill_brewer(palette = "Set1")
area+scale_fill_brewer(palette = "Set2")
area+scale_fill_brewer(palette = "Set3")
```

```{r}
plot<-qplot(brainwt,bodywt,data=msleep,log="xy")
plot+aes(colour=vore)+scale_colour_manual(values=c("red","orange","yellow","green","blue"))
colours<-c(carni="red","NA"="orange",insecti="yellow",herbi="green",omni="blue")
plot+aes(colour=vore)+scale_colour_manual(values=colours)
plot+aes(shape=vore)+scale_shape_manual(values=c(1,2,6,0,23))
```

```{r}
hubron<-data.frame(year=1875:1972,level=LakeHuron)
ggplot(hubron,aes(year))+
  geom_line(aes(y=level-5),colour="blue")+
  geom_line(aes(y=level+5),colour="red")
```

```{r}
ggplot(hubron,aes(year))+
  geom_line(aes(y=level-5,colour="below"))+
  geom_line(aes(y=level+5,colour="above"))
```

```{r}
ggplot(hubron,aes(year))+
  geom_line(aes(y=level-5,colour="below"))+
  geom_line(aes(y=level+5,colour="above"))+
  scale_colour_manual("Direction",
                      values=c("below"="blue","above"="red"))
```
