
---
title: "ggplot2 Elegant Graphics for Data Analysis"
subtitle: "ggplot2 数据分析与图形艺术"
author: "QinQin0912"
date: "2015年12月5日"
output: html_document
---

##第四章 用图层构建图像
```{r}
library(ggplot2)
p<-ggplot(diamonds,aes(carat,price,colour=cut))##这个图形对象在加上图层之前无法显示,因此你现在什么也看不见
```

```{r}
p<-p+layer(geom="point")
```

```{r}
p<-ggplot(diamonds,aes(x=carat))##该代码可以生成一个组距为2，铁青色的直方图
p<-p+layer(
  geom="bar",
  geom_params=list(fill="steelblue"),
  stat="bin",
  stat_params=list(binwidth=2)
)
p#layer(geom,geom_params,stat,stat_params,data,mapping,position)
```


```{r}
ggplot(msleep,aes(sleep_rem/sleep_total,awake))+geom_point()#散点图
##等价于
qplot(sleep_rem/sleep_total,awake,data=msleep)

##也可以给qplot增加图层
qplot(sleep_rem/sleep_total,awake,data=msleep)+geom_smooth()#增加平滑曲线
##等价于
qplot(sleep_rem/sleep_total,awake,data=msleep,geom=c("point","smooth"))
##或
ggplot(msleep,aes(sleep_rem/sleep_total,awake))+geom_point()+geom_smooth()
```

```{r}
library(scales)
bestfit<-geom_smooth(method="lm",se=F,colour=alpha("steelblue",0.5),size=2)
qplot(sleep_rem,sleep_total,data=msleep)+bestfit
qplot(awake,brainwt,data=msleep,log="y")+bestfit
qplot(bodywt,brainwt,data=msleep,log="xy")+bestfit
```

```{r}
p<-ggplot(mtcars,aes(mpg,wt,colour=cyl))+geom_point()
p
mtcars<-transform(mtcars,mpg=mpg^2)
p%+%mtcars #添加新的数据集以代替原来的数据集
##在更改数据集时,可以任意改变它的值和维数,但是如果将一个变量从离散型变成连续型或者从连续型和离散型,那么也需要改变相应的默认标度。
```

```{r}
aes(weight,height,colour=sqrt(age))#可以使用变量的函数值作为参数
```

```{r}
p<-ggplot(mtcars,aes(x=mpg,y=wt))
p+geom_point()
p+geom_point(aes(colour=factor(cyl)))#修改颜色
p+geom_point(aes(y=disp))#用disp修改y坐标

#添加aes(colour=cyl)相当于aes(mpg,wt,colour=cyl)
#修改aes(y=disp),相当于aes(mpg,disp)
#删除aes(y=NULL),相当于aes(mpg)
```

```{r}
p<-ggplot(mtcars,aes(mpg,wt))
p+geom_point(colour="darkblue")
```
v.s.
```{r}
p+geom_point(aes(colour="darkblue"))
```

```{r}
library(nlme)
p<-ggplot(Oxboys,aes(age,height,group=Subject))+geom_line()#多个分组与单个图形属性
p
```

```{r}
p+geom_smooth(aes(group=Subject),method="lm",se=F)#无意间给每一个男孩增加了一跳光滑线条
p+geom_smooth(aes(group=1),method="lm",se=F)#属于整体数据的线条
```

```{r}
boysbox<-ggplot(Oxboys,aes(Occasion,height))+geom_boxplot()
boysbox+geom_line(aes(group=Subject),colour="#3366FF")
#修改默认分组
```

```{r,echo=FALSE}
xgrid<-with(df,seq(min(x),max(x),length=50))
interp<-data.frame(
  x=xgrid,
  y=approx(df$x,df$y,xout=xgrid)$y,
  colour=approx(df$x,df$colour,xout=xgrid)$y
)
qplot(x,y,data=df,colour=colour,size=I(5))+geom_line(data=interp,size=2)

```

```{r}
ggplot(diamonds,aes(carat))+geom_histogram(aes(y=..density..),binwidth=0.1)
#生成变量的名字必须用..围起来.
qplot(carat,..density..,data=diamonds,geom="histogram",binwidth=0.1)
```

```{r}
d<-ggplot(diamonds,aes(carat))+xlim(0,3)
d+stat_bin(aes(ymax=..count..),binwidth = 0.1,geom="area")
d+stat_bin(aes(size=..density..),binwidth = 0.1,geom="point",position="identity")
d+stat_bin(aes(y=1,fill=..count..),binwidth = 0.1,geom="tile",position="identity")
```

```{r}
require(nlme,quiet=TRUE,warn.conflicts = FALSE)
model<-lme(height~age,data=Oxboys,random=~1+age|Subject)
oplot<-ggplot(Oxboys,aes(age,height,group=Subject))+geom_line()

age_grid<-seq(-1,1,length=10)
subjects<-unique(Oxboys$Subject)
preds<-expand.grid(age=age_grid,Subject=subjects)
preds$height<-predict(model,preds)

oplot+geom_line(data=preds,colour="#3366FF",size=0.4)

Oxboys$fitted<-predict(model)
Oxboys$resid<-with(Oxboys,fitted-height)
oplot%+%Oxboys+aes(y=resid)+geom_smooth(aes(group=1))
#残差不是随机分布

model2<-update(model,height~age+I(age^2))
Oxboys$fitted2<-predict(model2)
Oxboys$resid2<-with(Oxboys,fitted2 - height)
oplot%+%Oxboys+aes(y=resid2)+geom_smooth((aes(group=1)))
```
